---
apiVersion: v1
kind: Service
metadata:
  name: dsv-injector
spec:
  type: ClusterIP
  ports:
    - port: 8543
      targetPort: 18543
---
kind: Endpoints
apiVersion: v1
metadata:
  name: dsv-injector
subsets:
  - addresses:
      - ip: "192.168.1.1"
    ports:
      - port: 8543
