---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsv-injector
  namespace: default
  labels:
    app: dsv-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsv-injector
  template:
    metadata:
      labels:
        app: dsv-injector
      namespace: default
    spec:
      containers:
        - name: dsv-injector
          image: dsv-injector:latest
          imagePullPolicy: IfNotPresent # No pull required in Minikube
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 18543
---
apiVersion: v1
kind: Service
metadata:
  name: dsv-injector
  namespace: default
  labels:
    app: dsv-injector
spec:
  ports:
    - port: 8543
      targetPort: 18543
  selector:
    app: dsv-injector
  type: LoadBalancer
