changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{ .Body -}}'
body:
  block: true
kinds:
  - label: 🤖 CI & Build
    auto: patch
  - label: 🎉 New Product Feature
    auto: minor
  - label: ⬇️ Deprecated
    auto: minor
  - label: 🧪 Tests
    auto: patch
  - label: 🔨 Refactor
    auto: patch
  - label: 🐛 Bug Fix
    auto: patch
  - label: 🔥 Breaking Change
    auto: minor
  - label: 🔒 Security
    auto: patch
  - label: ⬆️ Dependencies
    auto: patch
  - label: 🔥 Major Version Change (Breaking Changes)
    auto: major
newlines:
  afterChange: 0
  afterChangelogHeader: 1
  afterChangelogVersion: 1
  afterComponent: 1
  afterFooterFile: 1
  afterFooter: 1
  afterHeaderFile: 1
  afterHeaderTemplate: 1
  afterKind: 1
  afterVersion: 1

  beforeChange: 0
  beforeChangelogVersion: 0
  beforeComponent: 0
  beforeFooterFile: 0
  beforeFooterTemplate: 0
  beforeHeaderFile: 0
  beforeHeaderTemplate: 0
  beforeKind: 1
  beforeVersion: 0
  endOfVersion: 0

replacements:
  # chart versions align with the release and get bumped by changie for us on `changie merge`.
  - path: 'charts/dsv-injector/Chart.yaml'
    find: 'version: .*'
    replace: 'version: {{.Version}}'
  - path: 'charts/dsv-syncer/Chart.yaml'
    find: 'version: .*'
    replace: 'version: {{.Version}}'
  # use pinned versions in the chart install examples as a best practice
  - path: 'charts/dsv-injector/Chart.yaml'
    find: "IMAGE_TAG='.*'"
    replace: "IMAGE_TAG='{{.Version}}'"
  - path: 'charts/dsv-syncer/Chart.yaml'
    find: "IMAGE_TAG='.*'"
    replace: "IMAGE_TAG='{{.Version}}'"
  # use pinned versions in the chart default values as a best practice
  - path: 'charts/dsv-injector/values.yaml'
    find: 'tag: .*'
    replace: 'tag: {{.Version}}'
  - path: 'charts/dsv-syncer/values.yaml'
    find: 'tag: .*'
    replace: 'tag: {{.Version}}'
