---
extends: default
# For all rules
ignore: |
  .markdownlint-cli2.yaml
  .licenses/
  docs/godocs/
  templates/
  charts/
rules:
  line-length: disable
  document-start: disable

  comments:
    require-starting-space: false
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: disable

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
