---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsv.fullname" . }}
  labels:
    {{- include "dsv.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webhookPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "dsv.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
