{{- $tlsCert := genSelfSignedCert (include "dsv.dnsname" .) nil (list (include "dsv.dnsname" .) (include "dsv.name" .)) (default 365 .Values.webhookCertExpireDays | int) -}}
{{- $existingTlsSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-tls" (include "dsv.name" .)) -}}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dsv.fullname" . }}
  labels:
    {{- include "dsv.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "dsv.fullname" . }}.{{ .Release.Namespace }}.svc
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["secrets"]
        scope: {{ default "*" .Values.webhookScope }}
    clientConfig:
{{- if eq .Values.service.type "ExternalName" }}
      caBundle: {{ .Values.caBundle }}
{{- else }}
      caBundle: {{ $tlsCert.Cert | b64enc }}
{{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "dsv.name" . }}
        path: {{ .Values.webhookUri }}
        port: {{ .Values.webhookPort }}
    admissionReviewVersions: ["v1"]
    sideEffects: {{ default "None" .Values.sideEffects }}
{{- if ne .Values.service.type "ExternalName" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/tls
data:
  tls.crt: {{ $tlsCert.Cert | b64enc }}
  tls.key: {{ $tlsCert.Key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsv.name" . }}-tls
  annotations:
    last-modified: {{ now | quote }}
data:
  cert.pem: {{ $tlsCert.Cert | b64enc }}
  key.pem: {{ $tlsCert.Key | b64enc }}
type: Opaque
{{- end }}
