{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dsv.name" . }}
  labels:
    {{- include "dsv.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "dsv.fullname" . }}.default.svc
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        apiVersions: ["v1", "v1beta1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secrets"]
    clientConfig:
      caBundle: {{ .Values.caBundle | b64enc }}
      service:
        name: {{ include "dsv.name" . }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.webhookUri }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" -}}
        port: {{ .Values.webhookPort }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: {{ default "None" .Values.sideEffects }}
{{- end }}
