{{- $tlsCert := genSelfSignedCert (include "dsv.dnsname" .) nil (list (include "dsv.dnsname" .) (include "dsv.name" .)) (default 365 .Values.webhookCertExpireDays | int) -}}
{{- $tlsSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-tls" (include "dsv.name" .)) -}}
---
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "dsv.name" . }}
  labels:
    {{- include "dsv.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "dsv.fullname" . }}.{{ .Release.Namespace }}.svc
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        apiVersions: ["v1", "v1beta1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secrets"]
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
        scope: {{ default "*" .Values.webhookScope }}
{{- end }}
    clientConfig:
{{- if $tlsSecret }}
      caBundle: {{ $tlsSecret.data.cert }}
{{- else }}
      caBundle: {{ $tlsCert.Cert | b64enc }}
{{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "dsv.name" . }}
        path: {{ .Values.webhookUri }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
        port: {{ .Values.webhookPort }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: {{ default "None" .Values.sideEffects }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsv.name" . }}-tls
data:
{{- if $tlsSecret }}
  cert: {{ $tlsSecret.data.cert }}
  key: {{ $tlsSecret.data.key }}
{{- else }}
  cert: {{ $tlsCert.Cert | b64enc }}
  key: {{ $tlsCert.Key | b64enc }}
type: Opaque
{{- end }}
