---
apiVersion: v2
name: dsv-injector
description: |
  A Helm chart for the Delinea DevOps Secrets Vault (DSV) Injector Mutating Webhook.

  ```shell
  NAMESPACE='dsv'
  CREDENTIALS_JSON_FILE='.cache/credentials.json' # replace with your credentials file
  IMAGE_REPOSITORY='docker.io/delineaxpm/dsv-k8s'
  IMAGE_TAG='v1.2.2' # use latest for test, but pin to a specific version for production

  helm install \
      --namespace $NAMESPACE \
      --create-namespace \
      --set-file credentialsJson=${CREDENTIALS_JSON_FILE} \
      --set image.repository=${IMAGE_REPOSITORY} \
      --set image.tag=${IMAGE_TAG} \
      --atomic \
      --timeout "5m" \
      --debug -v4 \ # optional --values ./myvaluesfile/values.yaml \
      dsv-injector ./charts/dsv-injector
  ```

keywords:
  - Delinea
  - DevOps
  - DSV
  - secrets
  - vault
type: application
version: v1.2.2
appVersion: latest
maintainers:
  - name: Sheldon Hull
  - name: Delinea DSV Team
