

# https://goreleaser.com/customization/docker/?h=scrat#how-it-works
# trunk-ignore(hadolint/DL3007)
FROM cgr.dev/chainguard/static:latest
COPY dsv-syncer /app/dsv-syncer
COPY dsv-injector /app/dsv-injector
