# trunk-ignore-all(trivy,checkov,gitleaks): ignore, examples file with hard coded values
---
apiVersion: v1
kind: Secret
metadata:
  name: user-domain-pass
  annotations:
    # dsv.delinea.com/credentials: app1 # or default if not using multiple credentials
    dsv.delinea.com/set-secret: 'tests:dsv-k8s:food'
type: Opaque
data:
  username: dW5tb2RpZmllZC11c2VybmFtZQ==
  domain: dW5tb2RpZmllZC1kb21haW4=
  password: dW5tb2RpZmllZC1wYXNzd29yZA==
  food: aW0gaHVuZ3J5IGFuZCB0aGlzIHNob3VsZCBiZSByZXBsYWNlZCB3aXRoIGdvb2QgZm9vZAo=
