---
name: assign
on:
  # pull_request: # For testing changes in branch
  pull_request_target:
    types: [opened, ready_for_review]
permissions:
  pull-requests: write
  contents: read # Because it needs to read the configuration file

env: # required for reassignment
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  assign:
    uses: delineaxpm/github-workflows/.github/workflows/lint.yml@main
    secrets: inherit
