---
name: test
env:
  DSV_K8S_TEST_CONFIG: ${{ secrets.DSV_TMG_CONFIG }}
  DSV_K8S_TEST_SECRET_PATH: /test/k8s/simple
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    uses: delineaxpm/github-workflows/.github/workflows/test.yml@main
    secrets: inherit
